name: JunkTycoon
version: '1.0'
description: A Roblox inspired junk collecting simulator for Minecraft
author: Pallux
main: com.pallux.junktycoon.JunkTycoon
api-version: '1.21'
depend:
  - Vault
softdepend:
  - PlayerPoints

commands:
  junktycoon:
    description: Main JunkTycoon command
    usage: /junktycoon
    aliases: [jt, junk]
    permission: junktycoon.use
  junkreload:
    description: Reload the JunkTycoon plugin
    usage: /junkreload
    permission: junktycoon.admin.reload
  boosters:
    description: Open the global boosters shop
    usage: /boosters
    aliases: [booster, shop]
    permission: junktycoon.boosters

permissions:
  junktycoon.use:
    description: Allows use of the JunkTycoon plugin
    default: true
  junktycoon.boosters:
    description: Allows use of the boosters shop
    default: true
  junktycoon.admin.reload:
    description: Allows reloading the plugin
    default: op
  junktycoon.admin.*:
    description: Gives all admin permissions
    default: op
    children:
      - junktycoon.admin.reload